### ISSUE TITLE
Gersemi does not seem to accept arguments when used via pre-commit

### ISSUE THREAD

**Issue by adamryczkowski** [BlankSpruce/gersemi#23]
```
  - repo: https://github.com/BlankSpruce/gersemi  # Formatter
    rev: 0.12.1
    hooks:
      - id: gersemi
        args: [--list-expansion, favour-inlining, --indent, '4']
 ```

I would like to customize the behaviour of gersemi in my pre-commit hooks. It looks as if putting anything in the `args` makes gersemi doing nothing. Probably it displays some message, presumably non-error, as returning non-zero code would be cought by the `pre-commit`. 

I have no problem with passing arguments to other pre-commit hooks I use.

P.S. It is enough to reproduce the error even by empty `args` property, like this:

```
  - repo: https://github.com/BlankSpruce/gersemi  # Formatter
    rev: 0.12.1
    hooks:
      - id: gersemi
        args: []
 ```
@DanielChabrowski

**Comment by adamryczkowski** [comment]
I found a solution/walkaround:

```
  - repo: https://github.com/BlankSpruce/gersemi  # Formatter
    rev: 0.12.1
    hooks:
      - id: gersemi
        args: [-i, --list-expansion, favour-inlining, --indent, '4']
```

When an argument is used (even an empty list), gersemi looks as entering the "check" mode. It only displays the formatted contents of the file. The walkaround is to force it into the "in-place" mode. 

Bug: `--in-place` verbose switch does not work. We need to use the short version `-i`.

I believe that this behaviour is unexpected and at the least needs to be addressed in the README, if not corrected at its root. 

The bug with ignoring of `--in-place` should be an easy fix.
